### ISSUE TITLE
`logot` only works with the default `loguru` logger?

### ISSUE THREAD

**Issue by DeadNews** [etianen/logot#117]
Thanks for your work.

Is it possible to configure `loguru` or does `logot` only work with a pre-configured default logger?

```py
# test_logger.py
import sys
from typing import Callable

import pytest
from logot import Logot, logged
from logot.loguru import LoguruCapturer
from loguru import logger
from rich.logging import RichHandler


@pytest.fixture(scope="session")
def logot_capturer() -> Callable[[], LoguruCapturer]:
    return LoguruCapturer


def test_capture(logot: Logot):
    """
    Works
    """
    # Log an error message with the default logger
    logger.info("foo bar")
    logot.assert_logged(logged.info("foo bar"))


def test_capture_setup_logger(logot: Logot):
    """
    Does not work
    """
    # Remove all handlers added so far, including the default one.
    logger.remove()
    # Console handler
    logger.add(sink=sys.stderr, level="DEBUG", format="{message}")

    # Log an error message
    logger.info("foo bar")
    logot.assert_logged(logged.info("foo bar"))


def test_capture_setup_logger_rich(logot: Logot):
    """
    Does not work
    """
    # Remove all handlers added so far, including the default one.
    logger.remove()
    # Console handler with rich formatting
    logger.add(
        sink=RichHandler(
            log_time_format="[%X]",
            rich_tracebacks=True,
            tracebacks_show_locals=True,
        ),
        level="DEBUG",
        format="{message}",
    )

    # Log an error message
    logger.info("foo bar")
    logot.assert_logged(logged.info("foo bar"))

```

Errors:

```console
$ test_capture_setup_logger 
AssertionError: Not logged:
[INFO] foo bar

Captured stderr call:
foo bar

$ test_capture_setup_logger_rich
AssertionError: Not logged:
[INFO] foo bar

Captured stderr call:
[01:02:03] INFO     foo bar                                    test_logger.py:42
```

Loguru [docs](https://loguru.readthedocs.io/en/stable/resources/recipes.html#avoiding-logs-to-be-printed-twice-on-the-terminal): 
> You should [remove()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.remove) it first if you plan to [add()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) another handler logging messages to the console, otherwise you may end up with duplicated logs.

**Comment by etianen** [comment]
Log capture works by adding a `loguru` handler using `loguru.logger.add()`. When you call `logger.remove()`, you're actually removing the `logot` log capturing handler! So that's what's breaking your log capture.

What you can do is this:

``` py
def test_capture_setup_logger():
    # Remove all handlers added so far, including the default one.
    logger.remove()
    # Console handler
    logger.add(sink=sys.stderr, level="DEBUG", format="{message}")

    with Logot().capturing() as logot:
        # Log an error message
        logger.info("foo bar")
        logot.assert_logged(logged.info("foo bar"))
```

So this isn't anything to do with the default handler... this is just about the order of `logger.remove()` and `Logot.capturing()` calls.

**Comment by etianen** [comment]
I'm curious what you're trying to test here? Is this just a simplified example? `logot` log capture doesn't care about any other added sinks, so your console handler isn't being tested. `logot` is there to test that a logging call has been made, not that it's been output to any particular sink.

If there is some general logger configuration you want to apply to all your tests, you can do it in a session fixture like this:

```py
@pytest.fixture(autouse=True, scope="session")
def _setup_loguru():
    logger.remove()
    logger.add(sink=sys.stderr, level="DEBUG", format="{message}")
```

This session fixture will be run *before* the logot fixture, so won't interfer with log capture.

**Comment by DeadNews** [comment]
>I'm curious what you're trying to test here? Is this just a simplified example?

Yes, I was trying to figure out why the actual test does not work.
The log shows that the `expected message` does not match the format of the `captured stderr call`. And I'm stuck on that.

In fact, there was an error in the test itself.

Everything works. Thank you very much.
